"""
Django settings for djangomonitor project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Use PyMySQL as MySQL driver
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-(qi_idh_-7-@6%-yr#zc7s_t&w30pxys-&_wwn)8i(-pv(!-m7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework',
    'corsheaders',
    'django.contrib.sites',
    # 'oauth2_provider',
    # 'social_django',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
   "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'allauth.account.middleware.AccountMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
]
SITE_ID = 1

# AUTHENTICATION_BACKENDS = (
#     'social_core.backends.google.GoogleOAuth2',
#     'django.contrib.auth.backends.ModelBackend',
# )

# ACCOUNT_AUTHENTICATION_METHOD = "email"
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_EMAIL_VERIFICATION = "optional"
# ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"

# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'your-google-oauth-key-here'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'your-google-oauth-secret-here'

CORS_ORIGIN_ALLOW_ALL = True

# Railway domains support
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173', 
    'http://127.0.0.1:5173', 
    'http://localhost:5174', 
    'http://127.0.0.1:5174',
    'https://railway.app',
    'http://railway.app',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "https://railway.app",
    "http://railway.app",
]

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,*.railway.app,*.railway.internal').split(',')


CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

ROOT_URLCONF = 'djangomonitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.parent.parent.joinpath('frontend')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangomonitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database configuration - MySQL (supports both Docker and Railway)
import dj_database_url

# Priority order:
# 1. MYSQL_URL (Railway MySQL variable reference) - PRIORITY
# 2. DATABASE_URL (Railway/Heroku standard)
# 3. Individual DB_* variables (local development)
# 4. Default SQLite

database_url = os.environ.get('MYSQL_URL') or os.environ.get('DATABASE_URL')

if database_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=600
        )
    }
    source = 'MYSQL_URL' if os.environ.get('MYSQL_URL') else 'DATABASE_URL'
    print(f"[settings.py] Using database URL from: {source}")
    if os.environ.get('MYSQL_URL'):
        print(f"[settings.py] ✅ Using Railway MySQL variable reference")
elif os.environ.get('DB_HOST'):
    # Local development with explicit MySQL
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.mysql'),
            'NAME': os.environ.get('DB_NAME', 'techtrack_db'),
            'USER': os.environ.get('DB_USER', 'techtrack_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'techtrack_secure_password'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }
    print(f"[settings.py] Using local MySQL at {os.environ.get('DB_HOST')}")
else:
    # Fallback: SQLite (shouldn't reach here if Railway vars are set correctly)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print("[settings.py] WARNING: Using SQLite - no database URL/variables found")

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings
# Trust the X-Forwarded-Proto header from nginx proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie security settings for proxy setup
# Important: For proxy setups, SameSite=None requires Secure=True in modern browsers
# But Django must see the request as HTTPS via X-Forwarded-Proto for this to work
CSRF_COOKIE_SECURE = False  # Set to False because backend sees HTTP (even though external is HTTPS)
SESSION_COOKIE_SECURE = False  # Set to False because backend sees HTTP
CSRF_COOKIE_SAMESITE = 'Lax'  # Use Lax instead of None for proxy compatibility
SESSION_COOKIE_SAMESITE = 'Lax'  # Use Lax instead of None

CSRF_COOKIE_HTTPONLY = False  # Needed for CSRF token access from JS
SESSION_COOKIE_HTTPONLY = True  # Keep session cookie httponly for security

STATICFILE_DIRS = (
    BASE_DIR.parent.parent.joinpath('frontend', 'dist'),

)

# Import os if joinpath does not work
# os.path.join instead of joinpath

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'wbtechnologies8@gmail.com' # Set this according to needs
EMAIL_HOST_PASSWORD = 'hsbt nzvu pgfy ceuz' # Django Mail app password (with spaces as given)

#   #yhcl jqnv nlwe hkkc

PASSWORD_RESET_TIMEOUT = 3600 # 1 hour

USE_TZ = True
TIME_ZONE = 'Asia/Manila'

# Updated at 2026-04-14 11:35:15
