"""
Django settings for djangomonitor project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Only load .env file in development (not on Render/production)
if not os.environ.get('RENDER'):
    from dotenv import load_dotenv
    load_dotenv()

# Use PyMySQL as MySQL driver
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-(qi_idh_-7-@6%-yr#zc7s_t&w30pxys-&_wwn)8i(-pv(!-m7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')


def _parse_csv_env(name, default_values, normalize=lambda value: value):
    raw = os.environ.get(name, '')
    if not raw:
        return default_values
    values = []
    for item in raw.split(','):
        item = item.strip()
        if not item:
            continue
        normalized = normalize(item)
        if normalized and normalized not in values:
            values.append(normalized)
    return values


def _normalize_host(value):
    value = value.strip().rstrip('/')
    if value.startswith('http://'):
        value = value[7:]
    elif value.startswith('https://'):
        value = value[8:]
    return value


def _normalize_origin(value):
    value = value.strip().rstrip('/')
    if value.startswith('http://') or value.startswith('https://'):
        return value
    return f'https://{value}'


def _merge_csv_env(name, default_values, normalize=lambda value: value):
    """Merge comma-separated env values with safe defaults without duplicates."""
    merged_values = list(default_values)
    for value in _parse_csv_env(name, [], normalize=normalize):
        if value not in merged_values:
            merged_values.append(value)
    return merged_values


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework',
    'corsheaders',
    'django.contrib.sites',
    # 'oauth2_provider',
    # 'social_django',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
   "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'allauth.account.middleware.AccountMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
]
SITE_ID = 1

# AUTHENTICATION_BACKENDS = (
#     'social_core.backends.google.GoogleOAuth2',
#     'django.contrib.auth.backends.ModelBackend',
# )

# ACCOUNT_AUTHENTICATION_METHOD = "email"
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_EMAIL_VERIFICATION = "optional"
# ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"

# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'your-google-oauth-key-here'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'your-google-oauth-secret-here'

CORS_ORIGIN_ALLOW_ALL = True

# Railway and Render domains support
default_allowed_hosts = [
    'localhost',
    '127.0.0.1',
    '.up.railway.app',
    '.railway.app',
    '.railway.internal',
    '.onrender.com',
    'techtrack-backend.render.com',
    'techtrack-backend-pynh.onrender.com',
]
render_external_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
if render_external_hostname and render_external_hostname not in default_allowed_hosts:
    default_allowed_hosts.append(render_external_hostname)

ALLOWED_HOSTS = _merge_csv_env('ALLOWED_HOSTS', default_allowed_hosts, normalize=_normalize_host)

default_cors_origins = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
    'http://localhost:5176',
    'http://127.0.0.1:5176',
    'https://frontend-service-production-ea39.up.railway.app',  # Railway frontend
    'https://techtrack-frontend.onrender.com',  # Render frontend (if needed later)
    'https://techhtrack-frontend.onrender.com',  # Alternative Render domain
]

frontend_url = os.environ.get('FRONTEND_URL', '').strip()
if frontend_url:
    default_cors_origins.append(_normalize_origin(frontend_url))

CORS_ALLOWED_ORIGINS = _merge_csv_env('CORS_ALLOWED_ORIGINS', default_cors_origins, normalize=_normalize_origin)

default_csrf_trusted_origins = list(default_cors_origins)
backend_url = os.environ.get('BACKEND_URL', '').strip()
if backend_url:
    default_csrf_trusted_origins.append(_normalize_origin(backend_url))

CSRF_TRUSTED_ORIGINS = _merge_csv_env('CSRF_TRUSTED_ORIGINS', default_csrf_trusted_origins, normalize=_normalize_origin)


CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

ROOT_URLCONF = 'djangomonitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.parent.parent.joinpath('frontend')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangomonitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database configuration - supports PostgreSQL (Render), MySQL (Docker), and SQLite
import dj_database_url

# Local dev: always use SQLite.
# Production/hosted environments should set USE_MYSQL=1 (or DATABASE_URL).
if os.environ.get('RENDER') or os.environ.get('USE_MYSQL', '').lower() in ('1','true','yes','y','on'):
    # HIGHEST PRIORITY: DATABASE_URL from environment (Render PostgreSQL or Railway)
    if os.environ.get('DATABASE_URL'):
        DATABASES = {
            'default': dj_database_url.config(
                default=os.environ.get('DATABASE_URL'),
                conn_max_age=600,
            )
        }
    # MEDIUM PRIORITY: Legacy MYSQL_URL (Railway MySQL)
    elif os.environ.get('MYSQL_URL') and os.environ.get('FORCE_MYSQL', '').lower() in ('1','true','yes'):
        DATABASES = {
            'default': dj_database_url.config(
                default=os.environ.get('MYSQL_URL'),
                conn_max_age=600
            )
        }
    else:
        # Fallback to MySQL-like env vars if present
        DATABASES = {
            'default': {
                'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.mysql'),
                'NAME': os.environ.get('DB_NAME', 'techtrack_db'),
                'USER': os.environ.get('DB_USER', 'techtrack_user'),
                'PASSWORD': os.environ.get('DB_PASSWORD', 'techtrack_secure_password'),
                'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
                'PORT': os.environ.get('DB_PORT', '3306'),
                'OPTIONS': {'charset': 'utf8mb4'},
            }
        }
else:
    # Use the existing techtrack_db if it exists, otherwise use db.sqlite3
    default_db_name = str(BASE_DIR / 'db.sqlite3')
    existing_db = str(BASE_DIR / 'techtrack_db')
    if os.path.exists(existing_db):
        default_db_name = existing_db
        print("[settings.py] Found existing techtrack_db, using it as the database")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.environ.get('DB_NAME', default_db_name),
        }
    }
    print("[settings.py] ✅ Using SQLite for local dev")


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# User-uploaded files (e.g., login background images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Backward-compatibility path for older fallback uploads saved outside MEDIA_ROOT.
LEGACY_LOGIN_BACKGROUND_ROOT = BASE_DIR / 'login_backgrounds'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings
# Trust the X-Forwarded-Proto header from nginx proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie security settings for cross-domain requests with credentials
# SameSite=None allows cookies to be sent in cross-site requests (needed for frontend-backend on different Railway subdomains)
# Secure=True required for SameSite=None in modern browsers - Django sees HTTPS via X-Forwarded-Proto
# Cookie `Secure` flags: enable in production (when DEBUG is False),
# disable in local DEBUG to allow cookies over plain HTTP during development.
# Cookie security settings
# Local dev must allow session cookies over HTTP between Vite (localhost:5174) and Django (localhost:8000)
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
if DEBUG:
    # In local development we serve over plain HTTP and use the Vite proxy.
    # Use 'Lax' so browsers will accept the cookie without Secure flag.
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SAMESITE = 'Lax'
else:
    # In production we need SameSite=None for cross-subdomain cookies and Secure=True
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SAMESITE = 'None'

CSRF_COOKIE_HTTPONLY = False  # Needed for CSRF token access from JS
SESSION_COOKIE_HTTPONLY = True  # Keep session cookie httponly for security (but still sent with credentials: include)

STATICFILE_DIRS = (
    BASE_DIR.parent.parent.joinpath('frontend', 'dist'),

)

# Import os if joinpath does not work
# os.path.join instead of joinpath

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'wbtechnologies8@gmail.com' # Set this according to needs
EMAIL_HOST_PASSWORD = 'hsbt nzvu pgfy ceuz' # Django Mail app password (with spaces as given)

#   #yhcl jqnv nlwe hkkc

PASSWORD_RESET_TIMEOUT = 3600 # 1 hour

USE_TZ = True
TIME_ZONE = 'Asia/Manila'

# Updated at 2026-04-14 11:35:15
