# Generated by Django 5.1.5 on 2025-06-02 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(choices=[('romeo', 'Romeo'), ('elma', 'Elma'), ('robert', 'Robert'), ('ricardo', 'Ricardo'), ('alexis', 'Alexis'), ('danny', 'Danny'), ('zenny', 'Zenny'), ('rogelio', 'Rogelio'), ('john_mark', 'John Mark'), ('jayson', 'Jayson'), ('jhonatan', 'Jhonatan'), ('juneybart', 'Juneybart')], max_length=100)),
                ('LastName', models.CharField(choices=[('alcantara', 'Alcantara'), ('bawaan', 'Bawaan'), ('ramirez', 'Ramirez'), ('cortez', 'Cortez'), ('lopez', 'Lopez'), ('gamutan', 'Gamutan'), ('ocampo', 'Ocampo'), ('indencio', 'Indencio'), ('nopia', 'Nopia'), ('ogaya', 'Ogaya'), ('maramias', 'Maramias')], max_length=100)),
                ('ProductionDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(choices=[('holder_torque_arm', 'HOLDER TORQUE ARM'), ('holder_step', 'HOLDER STEP'), ('gusset', 'GUSSET'), ('gusset_head_pipe', 'GUSSET HEAD PIPE'), ('arm_gusset', 'ARM GUSSET'), ('center_gusset', 'CENTER GUSSET'), ('plate_tank_fitting', 'PLATE TANK FITTING'), ('bracket_muffler', 'BRACKET MUFFLER'), ('bracket_tank', 'BRACKET TANK'), ('bracket_stand', 'BRACKET STAND'), ('bracket_stiffiner', 'BRACKET STIFFINER'), ('bracket_fender', 'BRACKET FENDER'), ('guide_chain', 'GUIDE CHAIN')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProcessName', models.CharField(choices=[('blanking', 'Blanking'), ('forming', 'Forming'), ('forming_1', 'Forming 1'), ('forming_2', 'Forming 2'), ('piercing', 'Piercing'), ('blank/pierce', 'Blank/Pierce'), ('welding_1', 'Welding 1'), ('welding_2', 'Welding 2'), ('cleaning', 'Cleaning'), ('rework', 'Rework'), ('retapping', 'Retapping'), ('spotweld', 'SpotWeld'), ('marking', 'Marking'), ('emboss/form', 'Emboss/Form'), ('coining', 'Coining')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active_task', 'Active Task'), ('completed', 'Completed'), ('failed', 'Failed')], help_text='Current state of the production process', max_length=50, verbose_name='Production Status')),
                ('employee', models.ManyToManyField(related_name='products', to='app.employees')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.requests')),
            ],
        ),
        migrations.CreateModel(
            name='DailyQuota',
            fields=[
                ('QuotaID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
    ]
