# Generated by Django 5.1.5 on 2025-06-11 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='ProductionDate',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='products',
            name='production_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='employees',
            name='FirstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='LastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='ProcessName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(help_text='Current state of the production process', max_length=50, verbose_name='Production Status'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='ProductName',
            field=models.CharField(max_length=100),
        ),
    ]
