# Generated by Django 5.1.5 on 2025-06-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_productiondate_employees_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquota',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
