# Generated by Django 5.1.5 on 2025-06-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dailyquota_date_alter_dailyquota_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessName',
            fields=[
                ('ProcessID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='ProcessName',
        ),
    ]
