# Generated by Django 5.1.5 on 2025-06-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_processname_remove_products_processname'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.processname'),
            preserve_default=False,
        ),
    ]
