# Generated by Django 5.1.5 on 2025-06-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_products_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('ProdID', models.AutoField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='requests',
            name='ProductName',
        ),
        migrations.AddField(
            model_name='requests',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.productname'),
            preserve_default=False,
        ),
    ]
