# Generated by Django 5.1.5 on 2025-06-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_productname_remove_requests_productname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
