# Generated by Django 5.1.5 on 2025-07-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_products_quantity'),
    ]

    operations = [
        migrations.DeleteModel(name='DailyQuota'),
    ]
