# Generated by Django 5.1.5 on 2025-07-16 09:19

from django.db import migrations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_worker_remove_products_employee_and_more'),
    ]

    operations = [
        # Fields already created in 0010, this migration is empty
    ]