# Generated by Django 5.1.5 on 2025-07-16 09:19

from django.db import migrations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_worker_remove_products_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='request',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='process_steps',
                to='app.requests',
            ),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='worker',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='app.worker',
            ),
        ),
    ]