# Generated by Django 5.1.5 on 2025-07-20 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20250716_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.processname')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productname')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('product_name', 'process')},
            },
        ),
    ]
