# Generated by Django 5.1.5 on 2025-07-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_processtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
