# Generated by Django 5.1.5 on 2025-08-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_productprocess_production_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprocess',
            name='worker',
        ),
        migrations.AddField(
            model_name='productprocess',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.worker'),
        ),
    ]
