# Generated by Django 5.1.5 on 2025-10-20 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_productprocess_worker_productprocess_workers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='product_name',
        ),
        migrations.AddField(
            model_name='productprocess',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived At'),
        ),
        migrations.AddField(
            model_name='requests',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived At'),
        ),
        migrations.AddField(
            model_name='requests',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encode_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requests',
            name='product_names',
            field=models.ManyToManyField(to='app.productname'),
        ),
        migrations.AddField(
            model_name='requests',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processname',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Process Name'),
        ),
        migrations.AlterField(
            model_name='processtemplate',
            name='step_order',
            field=models.PositiveIntegerField(verbose_name='Step Order'),
        ),
        migrations.AlterField(
            model_name='productprocess',
            name='completed_quota',
            field=models.PositiveIntegerField(default=0, verbose_name='Completed Quota'),
        ),
        migrations.AlterField(
            model_name='productprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='productprocess',
            name='defect_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Defect Count'),
        ),
        migrations.AlterField(
            model_name='productprocess',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
        migrations.AlterField(
            model_name='productprocess',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Production Date'),
        ),
        migrations.AlterField(
            model_name='productprocess',
            name='step_order',
            field=models.PositiveIntegerField(verbose_name='Step Order'),
        ),
        migrations.AlterField(
            model_name='productprocess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='FirstName',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='LastName',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=20, verbose_name='Role')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Account Created At')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
