# Generated by Django 5.1.5 on 2025-10-29 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_requests_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='quantity',
        ),
        migrations.CreateModel(
            name='RequestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='app.productname')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_products', to='app.requests')),
            ],
        ),
        migrations.AlterField(
            model_name='requests',
            name='product_names',
            field=models.ManyToManyField(through='app.RequestProduct', to='app.productname'),
        ),
    ]
