# Generated by Django 5.1.5 on 2025-10-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_requests_quantity_requestproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='product_names',
        ),
    ]
