# Generated by Django 5.1.5 on 2025-10-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_requests_product_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='product_names',
            field=models.ManyToManyField(through='app.RequestProduct', to='app.productname'),
        ),
    ]
