# Generated by Django 5.1.5 on 2025-11-13 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_requests_product_names'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productprocess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='request_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='app.requestproduct'),
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='request',
        ),
    ]
