# Generated by Django 5.1.5 on 2025-11-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_productprocess_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='deadline_extension',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline Extension'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='extension_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Requested At'),
        ),
    ]
