# Generated by Django 5.1.5 on 2025-11-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_productprocess_deadline_extension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprocess',
            name='deadline_extension',
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='extension_status',
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='requested_at',
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='deadline_extension',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline Extension'),
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='extension_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Requested At'),
        ),
    ]
