# Generated by Django 5.1.5 on 2025-11-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('archive', 'Archive'), ('extension_request', 'Extension Request'), ('extension_approved', 'Extension Approved'), ('extension_rejected', 'Extension Rejected')], max_length=50),
        ),
    ]
