# Generated by Django 5.1.5 on 2025-12-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestproduct',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived At'),
        ),
    ]
