# Generated by Django 5.1.5 on 2025-12-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_requestproduct_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
