# Generated by Django 5.1.5 on 2025-12-22 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_requests_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_quota', models.PositiveIntegerField(default=0)),
                ('defect_count', models.PositiveIntegerField(default=0)),
                ('logged_at', models.DateField(auto_now_add=True)),
                ('product_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productprocess')),
            ],
        ),
    ]
