# Generated by Django 5.1.5 on 2026-02-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configured_processes', to='app.productname'),
        ),
    ]
