# Generated by Django 5.1.5 on 2026-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_productprocess_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_created', 'Request Created'), ('project_started', 'Project Started'), ('task_status_updated', 'Task Status Updated'), ('product_completed', 'Product Completed'), ('request_completed', 'Request Completed'), ('deadline_approaching', 'Deadline Approaching')], max_length=50),
        ),
    ]
