# Generated by Django 6.0.2 on 2026-02-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_requestproduct_completed_at'),
        ('app', '0030_alter_notification_notification_type'),
    ]

    operations = [
    ]
