# Generated by Django 6.0.2 on 2026-02-25 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_merge_20260225_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_request',
            field=models.ForeignKey(blank=True, db_column='request_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.requests'),
        ),
    ]
