# Generated by Django 6.0.2 on 2026-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_notification_related_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('archive', 'Archive'), ('restore', 'Restore'), ('extension_request', 'Extension Request'), ('extension_approved', 'Extension Approved'), ('extension_rejected', 'Extension Rejected'), ('settings_update', 'Settings Update'), ('worker_create', 'Worker Create'), ('worker_update', 'Worker Update'), ('worker_delete', 'Worker Delete')], max_length=50),
        ),
    ]
