# Generated by Django 6.0.2 on 2026-02-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Terms Accepted'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terms Accepted At'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('archive', 'Archive'), ('restore', 'Restore'), ('extension_request', 'Extension Request'), ('extension_approved', 'Extension Approved'), ('extension_rejected', 'Extension Rejected'), ('settings_update', 'Settings Update'), ('worker_create', 'Worker Create'), ('worker_update', 'Worker Update'), ('worker_delete', 'Worker Delete'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update')], max_length=50),
        ),
    ]
