# Generated by Django 6.0.2 on 2026-02-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_userprofile_terms_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_request_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.requestproduct'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_created', 'Request Created'), ('project_started', 'Project Started'), ('task_status_updated', 'Task Status Updated'), ('product_completed', 'Product Completed'), ('request_completed', 'Request Completed'), ('deadline_approaching', 'Deadline Approaching'), ('extension_requested', 'Extension Requested'), ('extension_approved', 'Extension Approved'), ('extension_rejected', 'Extension Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager'), ('production_manager', 'Production Manager'), ('admin', 'Admin')], default='customer', max_length=20, verbose_name='Role'),
        ),
    ]
