# Generated by Django 6.0.2 on 2026-02-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_requests_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='process_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Process Name'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='process_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Process Number'),
        ),
    ]
