# Generated by Django 6.0.2 on 2026-03-02 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_productprocess_process_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Password Hash')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager'), ('production_manager', 'Production Manager'), ('admin', 'Admin')], default='customer', max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='Review Notes')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
