# Generated by Django 6.0.2 on 2026-03-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_accountsignuprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_created', 'Request Created'), ('request_approved', 'Request Approved'), ('request_declined', 'Request Declined'), ('project_started', 'Project Started'), ('task_status_updated', 'Task Status Updated'), ('product_completed', 'Product Completed'), ('request_completed', 'Request Completed'), ('deadline_approaching', 'Deadline Approaching'), ('extension_requested', 'Extension Requested'), ('extension_approved', 'Extension Approved'), ('extension_rejected', 'Extension Rejected')], max_length=50),
        ),
    ]
