# Generated by Django 6.0.2 on 2026-03-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Restored At'),
        ),
    ]
