# Generated by Django 6.0.2 on 2026-03-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_requests_restored_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestproduct',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Restored At'),
        ),
    ]
