# Generated by Django 6.0.2 on 2026-03-09 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_productprocess_tracking_and_requestproduct_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(choices=[('dimension', 'Dimension problem'), ('thickness', 'Thickness problem'), ('rush', 'Rush problem'), ('other', 'Other')], max_length=20, verbose_name='Defect Type')),
                ('defect_count', models.PositiveIntegerField(default=0, verbose_name='Defect Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_logs', to='app.productprocess')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
