# Generated by Django 6.0.2 on 2026-03-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_defectlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='login_background_image',
            field=models.FileField(blank=True, null=True, upload_to='login_backgrounds/'),
        ),
    ]
