# Generated by Django 6.0.3 on 2026-04-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_requestproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestproduct',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Restored At'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='process_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Process Number'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='process_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Process Name'),
        ),
    ]
