# Generated by Django 6.0.3 on 2026-04-02 15:32
# This migration is empty - columns already exist in database

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_requestproduct_quantity_and_more'),
    ]

    operations = [
        # All operations removed - columns already exist
    ]
