# Generated by Django 6.0.3 on 2026-04-02 15:41
# This migration is empty - columns already exist in database

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_add_missing_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # All operations removed - columns already exist
    ]
