# Generated by Django 6.0.3 on 2026-04-02 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_add_missing_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestproduct',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='quota_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Quota Last Updated'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='quota_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='defect_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Defect Last Updated'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='defect_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
