# Generated by Django 6.0.3 on 2026-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_add_more_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='defect_type',
            field=models.CharField(blank=True, choices=[('dimension', 'Dimension problem'), ('thickness', 'Thickness problem'), ('rush', 'Rush problem'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='defect_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
