# Generated by Django 5.1.5 on 2026-04-14 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_initialize_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelleddraftproduct',
            name='issuance_date',
            field=models.DateField(blank=True, help_text='Date the purchase order was issued', null=True),
        ),
        migrations.AddField(
            model_name='cancelleddraftproduct',
            name='issuance_no',
            field=models.CharField(blank=True, help_text='Purchase order issuance number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processtemplate',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Optional custom name for this step in this product', max_length=255, null=True, verbose_name='Custom Step Name'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='is_overtime',
            field=models.BooleanField(default=False, verbose_name='Is Overtime'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='ot_defect_logs',
            field=models.JSONField(blank=True, default=list, help_text="JSON array of OT defect logs: [{defect_type: '', defect_count: 0}]", verbose_name='OT Defect Logs'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='ot_enabled_date',
            field=models.DateField(blank=True, help_text='Date when OT was last enabled for this task - used to track daily reset', null=True, verbose_name='OT Enabled Date'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='ot_quota',
            field=models.PositiveIntegerField(default=0, verbose_name='OT Completed Quota'),
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='cancellation_progress',
            field=models.JSONField(blank=True, help_text='Progress snapshot at time of cancellation', null=True, verbose_name='Cancellation Progress'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('edit', 'Edited'), ('delete', 'Delete'), ('archive', 'Archive'), ('restore', 'Restore'), ('extension_request', 'Extension Request'), ('extension_approved', 'Extension Approved'), ('extension_rejected', 'Extension Rejected'), ('settings_update', 'Settings Update'), ('worker_create', 'Worker Create'), ('worker_update', 'Worker Update'), ('worker_delete', 'Worker Delete'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update')], max_length=50),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
