# Generated by Django 6.0.3 on 2026-04-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_add_cancelled_by_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprocess',
            name='defect_description',
            field=models.TextField(blank=True, null=True, verbose_name='Defect Description'),
        ),
        migrations.AlterField(
            model_name='productprocess',
            name='defect_type',
            field=models.CharField(blank=True, choices=[('dimension', 'Dimension problem'), ('thickness', 'Thickness problem'), ('rush', 'Rush problem'), ('other', 'Other')], max_length=20, null=True, verbose_name='Defect Type'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At'),
        ),
    ]
