# Generated by Django 5.1.5 on 2026-04-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_productprocess_is_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestproduct',
            name='cancellation_progress',
            field=models.JSONField(blank=True, help_text='Progress snapshot at time of cancellation', null=True, verbose_name='Cancellation Progress'),
        ),
    ]
