# Generated by Django 5.1.5 on 2026-04-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_add_cancellation_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='is_overtime',
            field=models.BooleanField(default=False, verbose_name='Is Overtime'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='ot_quota',
            field=models.PositiveIntegerField(default=0, verbose_name='OT Completed Quota'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='ot_defect_logs',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of OT defect logs: [{defect_type: \'\', defect_count: 0}]', verbose_name='OT Defect Logs'),
        ),
    ]
