# Generated by Django 5.1.5 on 2026-04-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_add_ot_daily_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('edit', 'Edited'), ('delete', 'Delete'), ('archive', 'Archive'), ('restore', 'Restore'), ('extension_request', 'Extension Request'), ('extension_approved', 'Extension Approved'), ('extension_rejected', 'Extension Rejected'), ('settings_update', 'Settings Update'), ('worker_create', 'Worker Create'), ('worker_update', 'Worker Update'), ('worker_delete', 'Worker Delete'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update')], max_length=50),
        ),
    ]
