# Generated by Django 5.1.5 on 2026-04-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelleddraftproduct',
            name='issuance_date',
            field=models.DateField(blank=True, help_text='Date the purchase order was issued', null=True),
        ),
        migrations.AddField(
            model_name='cancelleddraftproduct',
            name='issuance_no',
            field=models.CharField(blank=True, help_text='Purchase order issuance number', max_length=100, null=True),
        ),
    ]
