# Generated by Django 5.1.5 on 2026-04-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_cancelleddraftproduct_issuance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtemplate',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Optional custom name for this step in this product', max_length=255, null=True, verbose_name='Custom Step Name'),
        ),
    ]
